In [36]:
# @title L1 - Zadanie 1: Implementacja pojedynczego neuronu

import numpy as np

def neuron(input_vector: np.ndarray, weights_vector: np.ndarray, bias: float) -> float:
    """
        Oblicza odpowiedź pojedynczego neuronu zgodnie ze wzorem y = f(sum(wi * xi) + b)
        W tej prostej wersji, funkcja aktywacji f jest funkcją tożsamościową (f(x) = x)

        Args:
            input_vector: Wartości wejściowe neuronu (wektor)
            weights_vector: Wagi neuronu (wektor)
            bias: Wartość biasu

        ???:
            Wagi określają, jak ważny jest każdy sygnał wejściowy dla decyzji neuronu
            Bias jest stałą wartością dodawaną do sumy ważonej, która przesuwa próg aktywacji neuronu,
                ułatwiając (b > 0) lub utrudniając (b < 0 ) jego włączenie

        Returns:
            Wartość wyjściowa neuronu
    """

    if input_vector.shape != weights_vector.shape: # Czy ten sam rozmiar (kształt)
        raise ValueError("Wektory wejściowy i wag muszą mieć ten sam rozmiar.")

    weighted_sum = np.dot(input_vector, weights_vector)  # Obliczenie sumy ważonej (iloczyn skalarny - dot product)
    output_value = weighted_sum + bias  # Dodanie biasu

    return output_value

# Dane
input_data = np.array([0.5, 0.75, 0.1])
weights_data = np.array([0.1, 0.1, -0.3])
bias_value = 0.1

# Wywołanie funkcji
result = neuron(input_data, weights_data, bias_value)

print(f"Wektor wejściowy: {input_data}")
print(f"Wektor wag: {weights_data}")
print(f"Bias: {bias_value}")
print(f"Wynik neuronu (suma ważona + bias): {result:.5f}")

Wektor wejściowy: [0.5  0.75 0.1 ]
Wektor wag: [ 0.1  0.1 -0.3]
Bias: 0.1
Wynik neuronu (suma ważona + bias): 0.19500


In [42]:
# @title L1 - Zadanie 2: Implementacja jednowarstwowej sieci neuronowej

import numpy as np

def neural_network(input_vector: np.ndarray, weight_matrix: np.ndarray) -> np.ndarray:
    """
        Oblicza odpowiedź jednowarstwowej sieci neuronowej (Warstwy Gęstej)
            zgodnie ze wzorem output = W * x (mnożenie macierzowe)
        Zakłada się brak biasu i funkcji aktywacji (f(x) = x)

        Args:
            input_vector: Wartości wejściowe sieci (wektor 1D lub kolumnowy)
            weight_matrix: Macierz wag W, gdzie wiersze to neurony, a kolumny to wejścia (L_wyjscie x L_wejscie)

        Returns:
            Wektor wyjściowy sieci (odpowiedzi poszczególnych neuronów)
    """

    # 1. Liczba kolumn macierzy wag musi być równa liczbie elementów wejściowych
    num_inputs = input_vector.size
    num_weights_cols = weight_matrix.shape[1] # 0 - wiersze, 1 - kolumny, n - itd.

    if num_inputs != num_weights_cols:
        raise ValueError(f"Błąd wymiarów: Liczba kolumn w macierzy wag ({num_weights_cols}) musi być równa liczbie wejść ({num_inputs}).")

    # 2. Wektor wejściowy - konwersja na kolumnę
    input_column = input_vector.reshape(-1, 1) # np.reshape(-1, 1) zmienia (3,) na (3,1)

    # 3. Mnożenie macierzowe (wektoryzacja)
    output_vector = weight_matrix @ input_column # output = W @ x lub np.dot(W, x)
    # output_vector = np.dot(weight_matrix, input_column)

    # 4. Zwrócenie wyniku jako płaskiego wektora 1D
    return output_vector.flatten()

# Dane
input_data_x = np.array([0.5, 0.75, 0.1])
weight_data_W = np.array([
    [0.1, 0.1, -0.3],   # Wagi dla Neuronu 1
    [0.1, 0.2, 0.0],    # Wagi dla Neuronu 2
    [0.0, 0.7, 0.1],    # Wagi dla Neuronu 3
    [0.2, 0.4, 0.0],    # Wagi dla Neuronu 4
    [-0.3, 0.5, 0.1]    # Wagi dla Neuronu 5
])

# Wywołanie funkcji
network_output = neural_network(input_data_x, weight_data_W)

print(f"Macierz wag W (5x3):\n{weight_data_W}")
print("-" * 30)
print(f"Wektor wejściowy x (3x1): {input_data_x}")
print("-" * 30)
print(f"Wynik sieci neuronowej (output = W * x):\n{network_output}")

# Oczekiwany wynik
expected_output = np.array([0.095, 0.2, 0.535, 0.4, 0.235])

print("-" * 30)
# Sprawdzenie czy wynik jest zgodny z oczekiwaniami
if np.allclose(network_output, expected_output):
    print("Test sukces: Wynik jest zgodny z oczekiwanym rezultatem z instrukcji.")
else:
    print("Test uwaga: Wynik różni się od oczekiwanego.")
    print(f"Oczekiwany: {expected_output}")
    print(f"Otrzymany:  {network_output}")


# print("=" * 50)
# # Test: Sieć z 4 wejściami i 2 neuronami wyjściowymi
# input_test = np.array([1, 2, 3, 4]) # 4 wejścia
# # Macierz wag musi mieć 2 wiersze (2 neurony) i 4 kolumny (4 wejścia)
# weight_test = np.array([
#     [0.5, 0.1, -0.2, 0.0],  # Neuron A
#     [0.0, -1.0, 0.1, 0.5]   # Neuron B
# ])

# universal_output = neural_network(input_test, weight_test)

# print("TEST UNIWERSALNY (4 WEJŚCIA, 2 NEURONY)")
# print(f"Wynik sieci:\n{universal_output}")

Macierz wag W (5x3):
[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   0.7  0.1]
 [ 0.2  0.4  0. ]
 [-0.3  0.5  0.1]]
------------------------------
Wektor wejściowy x (3x1): [0.5  0.75 0.1 ]
------------------------------
Wynik sieci neuronowej (output = W * x):
[0.095 0.2   0.535 0.4   0.235]
------------------------------
Test sukces: Wynik jest zgodny z oczekiwanym rezultatem z instrukcji.


In [43]:
# @title L1 - Zadanie 3: Implementacja głębokiej sieci neuronowej

import numpy as np

def deep_neural_network(input_vector: np.ndarray, list_of_weight_matrices: list[np.ndarray]) -> np.ndarray:
    """
        Oblicza odpowiedź głębokiej (wielo-warstwowej) sieci neuronowej
            poprzez sekwencyjne mnożenie macierzowe

        Args:
            input_vector: Wartości wejściowe dla pierwszej warstwy
            list_of_weight_matrices: Lista macierzy wag, gdzie każda macierz reprezentuje jedną warstwę
                                    [Wagi_Warstwa_Ukryta, Wagi_Warstwa_Wyjsciowa, ...]

        Returns:
            Wektor wyjściowy ostatniej warstwy sieci
    """

    # 1. Czy jest jakakolwiek warstwa
    if not list_of_weight_matrices:
        return input_vector.flatten()

    # 2. Inicjalizacja: bieżące wejście to wejście sieci
    current_input = input_vector.reshape(-1, 1)

    # 3. Iteracja przez wszystkie warstwy (macierze wag)
    for i, weight_matrix in enumerate(list_of_weight_matrices):
        # Sprawdzenie wymiarów: kolumny W muszą pasować do wierszy x
        num_inputs = current_input.shape[0]
        num_weights_cols = weight_matrix.shape[1]

        if num_inputs != num_weights_cols:
             raise ValueError(
                f"Błąd wymiarów w warstwie {i+1}: Liczba wejść ({num_inputs}) "
                f"musi być równa liczbie kolumn w macierzy wag ({num_weights_cols})."
            )

        # Obliczenie wyjścia bieżącej warstwy i wejścia dla następnej warstwy
        current_output = weight_matrix @ current_input
        current_input = current_output

    # Zwrócenie wyniku 1D
    return current_output.flatten()

# Dane:
# Wektor wejściowy x (Wzór 4 - ten sam co w Zadaniu 2)
input_data_x = np.array([0.5, 0.75, 0.1])

# Macierz wag Wh - Warstwa Ukryta (5 neuronów) (Wzór 6)
weights_hidden_Wh = np.array([
    [0.1, 0.1, -0.3],   # Ukryty 1
    [0.1, 0.2, 0.0],    # Ukryty 2
    [0.0, 0.7, 0.1],    # Ukryty 3
    [0.2, 0.4, 0.0],    # Ukryty 4
    [-0.3, 0.5, 0.1]    # Ukryty 5
])

# Macierz wag Wy - Warstwa Wyjściowa (3 neurony) (Wzór 7)
# 3 wiersze (wyjścia) x 5 kolumn (wejścia z warstwy ukrytej)
weights_output_Wy = np.array([
    [0.7, 0.9, -0.4, 0.8, 0.1],   # Wyjście 1
    [0.8, 0.5, 0.3, 0.1, 0.0],    # Wyjście 2
    [-0.3, 0.9, 0.3, 0.1, -0.2]   # Wyjście 3
])

# Lista macierzy wag dla głębokiej sieci (sekwencja W_h, W_y)
weights_list = [weights_hidden_Wh, weights_output_Wy]

# Wywołanie funkcji
final_output = deep_neural_network(input_data_x, weights_list)

print(f"Wektor wejściowy x: {input_data_x}")
print("-" * 30)
print(f"Wagi Warstwy Ukrytej (Wh):\n{weights_hidden_Wh}")
print(f"Wagi Warstwy Wyjściowej (Wy):\n{weights_output_Wy}")
print("-" * 30)
print(f"Wynik sieci neuronowej (Layer Output):\n{final_output}")

expected_output = np.array([0.376, 0.3765, 0.305])

print("-" * 30)
if np.allclose(final_output, expected_output, atol=1e-4): # atol=1e-4 ze względu na zaokrąglenia w przykładzie
    print("Test sukces: Wynik jest zgodny z oczekiwanym rezultatem z instrukcji.")
else:
    print("Test uwaga: Wynik różni się od oczekiwanego.")
    print(f"Oczekiwany: {expected_output}")
    print(f"Otrzymany:  {final_output}")

# print("=" * 50)
# print("TEST UNIWERSALNY: Sieć 4 wejścia -> 3 ukryte -> 2 wyjścia (4x3x2)")

# # DANE WEJŚCIOWE (4 wejścia)
# input_data_universal = np.array([1.0, 0.5, 0.2, 0.1])

# # WAGI WARSTWY UKRYTEJ (Wh: 3 neurony x 4 wejścia)
# weights_hidden_Wh = np.array([
#     [0.1, 0.2, 0.1, 0.0],  # Neuron 1
#     [0.5, -0.1, 0.3, 0.2], # Neuron 2
#     [0.0, 0.4, -0.2, 0.5]  # Neuron 3
# ])

# # WAGI WARSTWY WYJŚCIOWEJ (Wy: 2 neurony x 3 wejścia z poprzedniej warstwy)
# weights_output_Wy = np.array([
#     [1.0, 0.5, 0.1],      # Wyjście 1
#     [0.2, -0.1, 0.8]      # Wyjście 2
# ])

# weights_list_universal = [weights_hidden_Wh, weights_output_Wy]

# # Wywołanie funkcji
# final_output_universal = deep_neural_network(input_data_universal, weights_list_universal)

# print(f"Wektor wejściowy: {input_data_universal}")
# print("-" * 30)
# print(f"Wynik sieci (długość: {final_output_universal.size}):\n{final_output_universal}")

# if final_output_universal.shape[0] == weights_output_Wy.shape[0]:
#     print("Test sukces: Długość wyjścia jest poprawna (równa liczbie neuronów wyjściowych).")
# else:
#     print("Test uwaga: Błąd w wymiarach wyjścia.")

Wektor wejściowy x: [0.5  0.75 0.1 ]
------------------------------
Wagi Warstwy Ukrytej (Wh):
[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   0.7  0.1]
 [ 0.2  0.4  0. ]
 [-0.3  0.5  0.1]]
Wagi Warstwy Wyjściowej (Wy):
[[ 0.7  0.9 -0.4  0.8  0.1]
 [ 0.8  0.5  0.3  0.1  0. ]
 [-0.3  0.9  0.3  0.1 -0.2]]
------------------------------
Wynik sieci neuronowej (Layer Output):
[0.376  0.3765 0.305 ]
------------------------------
Test sukces: Wynik jest zgodny z oczekiwanym rezultatem z instrukcji.


In [3]:
# @title L1 - Zadanie 4: Klasa SequentialModel (Modułowa Sieć Neuronowa)

import numpy as np


class SequentialModel:
    """
        Modułowa sieć neuronowa z warstwami w pełni połączonymi (Fully Connected)

        Umożliwia budowanie sieci o dowolnej architekturze poprzez dynamiczne dodawanie warstw
        Automatycznie generuje losowe wagi dla każdej warstwy i zarządza przepływem danych
    """

    def __init__(self, input_size: int):
        """
            Inicjalizacja modelu z określoną liczbą wejść

            Args:
                input_size: Liczba neuronów wejściowych (wymiar wektora wejściowego)
        """
        self.input_size = input_size  # Liczba wejść do sieci
        self.layers = []  # Lista przechowująca macierze wag dla każdej warstwy
        # Historia rozmiarów warstw [input, hidden1, hidden2, ..., output]
        self.layer_sizes = [input_size]

    def add_layer(self, n: int, weight_range: tuple[float, float] = (-1.0, 1.0)) -> None:
        """
            Dodaje warstwę w pełni połączoną z n neuronami do sieci.

            Args:
                n: Liczba neuronów w dodawanej warstwie
                weight_range: Krotka (min, max) określająca zakres losowania wag (domyślnie [-1, 1])
        """
        # Liczba wejść dla nowej warstwy = liczba neuronów w poprzedniej warstwie
        previous_layer_size = self.layer_sizes[-1]

        # Losowanie wag z zakresu [min, max] dla macierzy (n x previous_layer_size)
        weight_min, weight_max = weight_range
        weight_matrix = np.random.uniform(
            low=weight_min,
            high=weight_max,
            size=(n, previous_layer_size)
        )

        # Dodanie macierzy wag do listy warstw
        self.layers.append(weight_matrix)

        # Aktualizacja historii rozmiarów warstw
        self.layer_sizes.append(n)

    def predict(self, input_vector: np.ndarray) -> np.ndarray:
        """
            Oblicza odpowiedź sieci dla podanego wektora wejściowego.

            Przepuszcza dane przez wszystkie warstwy sekwencyjnie (forward pass).

            Args:
                input_vector: Wektor wejściowy (1D array)

            Returns:
                Wektor wyjściowy ostatniej warstwy (odpowiedź sieci)
        """
        # Walidacja wymiarów wejścia
        if input_vector.size != self.input_size:
            raise ValueError(
                f"Błąd wymiarów: Oczekiwano {self.input_size} wejść, "
                f"otrzymano {input_vector.size}"
            )

        # Walidacja istnienia warstw
        if not self.layers:
            raise ValueError(
                "Sieć nie ma żadnych warstw. Użyj add_layer() aby dodać warstwy.")

        # Inicjalizacja: aktualne wejście jako kolumna
        current_input = input_vector.reshape(-1, 1)

        # Propagacja przez wszystkie warstwy
        for weight_matrix in self.layers:
            current_output = weight_matrix @ current_input  # Mnożenie macierzowe
            current_input = current_output  # Wyjście staje się wejściem dla następnej warstwy

        # Zwrócenie wyniku jako płaski wektor 1D
        return current_output.flatten()

    def save_weights(self, file_name: str) -> None:
        """
            Zapisuje wagi wszystkich warstw do pliku .npz (format NumPy).

            Args:
                file_name: Nazwa pliku (bez rozszerzenia lub z .npz)
        """
        # Usunięcie rozszerzenia jeśli zostało podane (np.savez doda .npz automatycznie)
        if file_name.endswith('.npz'):
            file_name = file_name[:-4]

        # Konwersja listy macierzy na słownik z kluczami 'layer_0', 'layer_1', ...
        weights_dict = {f'layer_{i}': weight_matrix for i,
                        weight_matrix in enumerate(self.layers)}

        # Zapisz rozmiary warstw dla walidacji przy ładowaniu
        weights_dict['layer_sizes'] = np.array(self.layer_sizes)

        # Zapis do pliku
        np.savez(file_name, **weights_dict)
        # print(f"Wagi zapisane do pliku: {file_name}.npz")

    def load_weights(self, file_name: str) -> None:
        """
            Odczytuje wagi z pliku .npz i ustawia je w sieci

            Args:
                file_name: Nazwa pliku (z lub bez rozszerzenia .npz)
        """
        # Dodanie rozszerzenia jeśli brakuje
        if not file_name.endswith('.npz'):
            file_name += '.npz'

        # Wczytanie danych z pliku
        loaded_data = np.load(file_name)

        # Odczyt rozmiarów warstw (jeśli dostępne)
        if 'layer_sizes' in loaded_data:
            loaded_layer_sizes = loaded_data['layer_sizes']
            # Walidacja zgodności rozmiarów wejściowych
            if loaded_layer_sizes[0] != self.input_size:
                raise ValueError(
                    f"Niezgodność rozmiaru wejścia: Model ma {self.input_size} wejść, "
                    f"plik zawiera wagi dla {loaded_layer_sizes[0]} wejść"
                )

        # Odczyt macierzy wag (layer_0, layer_1, ...)
        self.layers = []
        layer_index = 0
        while f'layer_{layer_index}' in loaded_data:
            self.layers.append(loaded_data[f'layer_{layer_index}'])
            layer_index += 1

        # Rekonstrukcja layer_sizes na podstawie wczytanych wag
        self.layer_sizes = [self.input_size]
        for weight_matrix in self.layers:
            self.layer_sizes.append(weight_matrix.shape[0])

        # print(f"Wagi wczytane z pliku: {file_name}")
        # print(f"   Architektura: {' -> '.join(map(str, self.layer_sizes))}")


# ========================================
# DEMO: Budowanie i testowanie sieci
# ========================================

print("=" * 60)
print("DEMO 1: Prosta sieć 3 wejścia -> 5 ukrytych -> 3 wyjścia")
print("=" * 60)

# Utworzenie modelu z 3 wejściami
model = SequentialModel(input_size=3)

# Dodanie warstwy ukrytej (5 neuronów)
model.add_layer(n=5, weight_range=(-0.5, 0.5))

# Dodanie warstwy wyjściowej (3 neurony)
model.add_layer(n=3, weight_range=(-1.0, 1.0))

# Dane wejściowe (te same co w poprzednich zadaniach)
input_data = np.array([0.5, 0.75, 0.1])

# Predykcja
output = model.predict(input_data)

print(f"\nWejście: {input_data}")
print(f"Architektura: {' -> '.join(map(str, model.layer_sizes))}")
print(f"Wyjście: {output}")

# ========================================
# DEMO 2: Zapis i odczyt wag
# ========================================

print("\n" + "=" * 60)
print("DEMO 2: Zapis i odczyt wag z pliku")
print("=" * 60)

# Zapis wag do pliku
model.save_weights("model_weights")

# Tworzenie nowego modelu z tą samą architekturą
model_loaded = SequentialModel(input_size=3)
model_loaded.add_layer(n=5)  # Dodajemy warstwy (wagi zostaną nadpisane)
model_loaded.add_layer(n=3)

# Wczytanie wag z pliku
model_loaded.load_weights("model_weights.npz")

# Sprawdzenie czy wagi są identyczne
output_loaded = model_loaded.predict(input_data)
print(f"\nWejście: {input_data}")
print(f"Wyjście (model oryginalny): {output}")
print(f"Wyjście (model wczytany):   {output_loaded}")

if np.allclose(output, output_loaded):
    print("\nTest sukces: Wagi zostały poprawnie zapisane i wczytane!")
else:
    print("\nTest uwaga: Wyjścia różnią się (problem z zapisem/odczytem)")

# ========================================
# DEMO 3: Głęboka sieć (4 warstwy)
# ========================================

print("\n" + "=" * 60)
print("DEMO 3: Głęboka sieć 4 wejścia -> 8 -> 6 -> 4 -> 2 wyjścia")
print("=" * 60)

# Utworzenie głębokiej sieci
deep_model = SequentialModel(input_size=4)
deep_model.add_layer(n=8, weight_range=(-0.3, 0.3))   # Warstwa ukryta 1
deep_model.add_layer(n=6, weight_range=(-0.5, 0.5))   # Warstwa ukryta 2
deep_model.add_layer(n=4, weight_range=(-0.2, 0.2))   # Warstwa ukryta 3
deep_model.add_layer(n=2, weight_range=(-1.0, 1.0))   # Warstwa wyjściowa

# Dane wejściowe (4 elementy)
input_deep = np.array([1.0, 0.5, 0.2, 0.1])

# Predykcja
output_deep = deep_model.predict(input_deep)

print(f"\nWejście: {input_deep}")
print(f"Architektura: {' -> '.join(map(str, deep_model.layer_sizes))}")
print(f"Wyjście: {output_deep}")

print("\n" + "=" * 60)
print("Wszystkie testy zakończone sukcesem!")
print("=" * 60)

DEMO 1: Prosta sieć 3 wejścia -> 5 ukrytych -> 3 wyjścia

Wejście: [0.5  0.75 0.1 ]
Architektura: 3 -> 5 -> 3
Wyjście: [0.08194274 0.0975305  0.41521748]

DEMO 2: Zapis i odczyt wag z pliku

Wejście: [0.5  0.75 0.1 ]
Wyjście (model oryginalny): [0.08194274 0.0975305  0.41521748]
Wyjście (model wczytany):   [0.08194274 0.0975305  0.41521748]

Test sukces: Wagi zostały poprawnie zapisane i wczytane!

DEMO 3: Głęboka sieć 4 wejścia -> 8 -> 6 -> 4 -> 2 wyjścia

Wejście: [1.  0.5 0.2 0.1]
Architektura: 4 -> 8 -> 6 -> 4 -> 2
Wyjście: [-0.00701384 -0.07861146]

Wszystkie testy zakończone sukcesem!
